In [3]:
print("Jupyter 커널 연결 확인!")
import pandas as pd, numpy as np, matplotlib, seaborn as sns
print("pandas:", pd.__version__)
print("numpy:", np.__version__)

Jupyter 커널 연결 확인!
pandas: 3.0.5
numpy: 2.5.2

In [4]:
import oracledb
import pandas as pd

# 접속 정보 (실제 값으로 교체)
USER = "python_user"
PASSWORD = "54321"
DSN = "localhost:1521/XE"  # host:port/service_name

conn = oracledb.connect(user=USER, password=PASSWORD, dsn=DSN)
print("Oracle 연결 성공!")

# 첫 쿼리 실행
query = "SELECT * FROM DELIVERY_ORDERS"
df = pd.read_sql(query, conn)
print(df.head()) 
df.head()

Oracle 연결 성공!
   ORDER_ID MENU_NAME CATEGORY  PRICE  RATING REGION ORDER_DATE
0         1       떡볶이       분식   9000     4.5    강남구 2026-08-01
1         2        치킨       치킨  22000     4.8    서초구 2026-08-02
2         3        피자       피자  25000     4.2    강남구 2026-08-03
3         4       짜장면       중식   8000     4.0    송파구 2026-08-04
4         5       마라탕       중식  13000     4.6    강남구 2026-08-05

C:\Users\soldesk\AppData\Local\Temp\ipykernel_21436\2414369904.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   ORDER_ID MENU_NAME CATEGORY  PRICE  RATING REGION ORDER_DATE
0         1       떡볶이       분식   9000     4.5    강남구 2026-08-01
1         2        치킨       치킨  22000     4.8    서초구 2026-08-02
2         3        피자       피자  25000     4.2    강남구 2026-08-03
3         4       짜장면       중식   8000     4.0    송파구 2026-08-04
4         5       마라탕       중식  13000     4.6    강남구 2026-08-05

In [18]:
import os
from dotenv import load_dotenv

# .env 파일을 읽어오도록 반드시 실행해 주어야 합니다!
load_dotenv()

True

In [19]:
USER = os.getenv("ORACLE_USER")
PASSWORD = os.getenv("ORACLE_PASSWORD")
DSN = os.getenv("ORACLE_DSN")

In [20]:
with oracledb.connect(user=USER, password=PASSWORD, dsn=DSN) as conn:
    df=pd.read_sql("SELECT * FROM DELIVERY_ORDERS", conn)
# with문 블록을 벗어나는 순간 자동으로 conn.close()가 호출되어 안정적임

print("연결 및 쿼리 성공! 데이터 shape:", df.shape)
df.head()

연결 및 쿼리 성공! 데이터 shape: (7, 7)

C:\Users\soldesk\AppData\Local\Temp\ipykernel_21436\3488849678.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("SELECT * FROM DELIVERY_ORDERS", conn)

   ORDER_ID MENU_NAME CATEGORY  PRICE  RATING REGION ORDER_DATE
0         1       떡볶이       분식   9000     4.5    강남구 2026-08-01
1         2        치킨       치킨  22000     4.8    서초구 2026-08-02
2         3        피자       피자  25000     4.2    강남구 2026-08-03
3         4       짜장면       중식   8000     4.0    송파구 2026-08-04
4         5       마라탕       중식  13000     4.6    강남구 2026-08-05

In [ ]:
# 오라클 실행식
-- 테이블 생성
CREATE TABLE DELIVERY_ORDERS (
    ORDER_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENU_NAME    VARCHAR2(50),
    CATEGORY     VARCHAR2(30),
    PRICE        NUMBER,
    RATING       NUMBER(2,1),
    REGION       VARCHAR2(30),
    ORDER_DATE   DATE
);

-- 샘플 데이터 삽입
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('떡볶이', '분식', 9000, 4.5, '강남구', DATE '2026-08-01');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('치킨', '치킨', 22000, 4.8, '서초구', DATE '2026-08-02');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('피자', '피자', 25000, 4.2, '강남구', DATE '2026-08-03');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짜장면', '중식', 8000, 4.0, '송파구', DATE '2026-08-04');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('마라탕', '중식', 13000, 4.6, '강남구', DATE '2026-08-05');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('돈까스', '일식', 11000, 4.3, '서초구', DATE '2026-08-06');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('탕수육', '중식', 18000, 4.4, '송파구', DATE '2026-08-07');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('떡볶이', '분식', 8500, 4.3, '강남구', DATE '2026-08-08');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('순대', '분식', 7000, 4.1, '서초구', DATE '2026-08-08');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('치킨', '치킨', 21000, 4.7, '강남구', DATE '2026-08-09');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('양념치킨', '치킨', 23000, 4.9, '송파구', DATE '2026-08-09');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('반반치킨', '치킨', 22000, 4.6, '서초구', DATE '2026-08-10');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('피자', '피자', 24000, 4.0, '강남구', DATE '2026-08-10');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('포테이토피자', '피자', 27000, 4.4, '송파구', DATE '2026-08-11');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('불고기피자', '피자', 26000, 4.3, '서초구', DATE '2026-08-11');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짜장면', '중식', 7500, 3.9, '강남구', DATE '2026-08-12');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짬뽕', '중식', 9000, 4.2, '송파구', DATE '2026-08-12');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('마라탕', '중식', 12500, 4.5, '강남구', DATE '2026-08-13');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('탕수육', '중식', 19000, 4.6, '서초구', DATE '2026-08-13');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('돈까스', '일식', 10500, 4.2, '송파구', DATE '2026-08-14');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('초밥세트', '일식', 28000, 4.8, '강남구', DATE '2026-08-14');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('우동', '일식', 8000, 4.0, '서초구', DATE '2026-08-15');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('라멘', '일식', 11000, 4.4, '송파구', DATE '2026-08-15');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('떡볶이', '분식', 9500, 4.6, '서초구', DATE '2026-08-16');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('김밥', '분식', 5000, 4.0, '강남구', DATE '2026-08-16');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('치킨', '치킨', 22000, 4.5, '송파구', DATE '2026-08-17');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('피자', '피자', 25500, 4.1, '강남구', DATE '2026-08-17');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짜장면', '중식', 8000, 4.1, '서초구', DATE '2026-08-18');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('돈까스', '일식', 11500, 4.3, '송파구', DATE '2026-08-18');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('마라탕', '중식', 13500, 4.7, '강남구', DATE '2026-08-19');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('초밥세트', '일식', 29000, 4.9, '서초구', DATE '2026-08-19');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('떡볶이', '분식', 9000, 4.4, '송파구', DATE '2026-08-20');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('치킨', '치킨', 23500, 4.8, '강남구', DATE '2026-08-20');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('피자', '피자', 26500, 4.2, '서초구', DATE '2026-08-21');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짬뽕', '중식', 9500, 4.3, '송파구', DATE '2026-08-21');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('우동', '일식', 8500, 4.1, '강남구', DATE '2026-08-22');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('김밥', '분식', 5500, 4.2, '서초구', DATE '2026-08-22');
COMMIT;